collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.7849463
color:
  saturation: 0.3405018
  brandStrength: 0.8189964
  lightness: 0.9444444
  brandColors:
    - '#8CC5B0'
    - '#FF7665'
    - '#9C2817'
    - '#FFFFFF'
    - '#159099'
  rhythmicContrast: 0.6505376
layout_spectrum: 1
name: Adam Claxon
